regions: # On entering a region teleport there -> <regionName>[x,y,z]
  survival: [ 20, 20, 20 ]
  return-survival: [ 0, 0, 0 ]
portals: # On entering  a portal remove and teleport there -> <portalName> [serverName]
  portal-sand: [10, 10, 20, 90, 0]
  portal-snow: [10, 10, 20, 90, 0]